### ISSUE TITLE
Server breaks in random moment

### ISSUE THREAD

**Issue by yuriizinets** [yuriizinets/translator#1]
```
5ed318, 0x1, 0x1, 0x0, 0x0, 0xaced20, 0xc000850270, ...)

/go/pkg/mod/github.com/bregydoc/gtranslate@v0.0.0-20191225024717-45b28d4fda86/token.go:29 +0x19a

github.com/bregydoc/gtranslate.get(0x3, 0xaced20, 0xc000850270, 0x3, 0xaced20, 0xc0003fba40, 0x0, 0x0)

/go/pkg/mod/github.com/bregydoc/gtranslate@v0.0.0-20191225024717-45b28d4fda86/token.go:136 +0xce

github.com/bregydoc/gtranslate.translate(0xc000a18000, 0xba, 0xc0000a2598, 0x2, 0xc0000a259a, 0x2, 0xc0000b0001, 0x2, 0x0, 0x203000, ...)

/go/pkg/mod/github.com/bregydoc/gtranslate@v0.0.0-20191225024717-45b28d4fda86/apiv2.go:46 +0x11c

github.com/bregydoc/gtranslate.TranslateWithParams(0xc000a18000, 0xba, 0xc0000a2598, 0x2, 0xc0000a259a, 0x2, 0x0, 0x0, 0xc0005ed978, 0x4b9893, ...)

/go/pkg/mod/github.com/bregydoc/gtranslate@v0.0.0-20191225024717-45b28d4fda86/gtranslate.go:28 +0x8f

github.com/yuriizinets/translator/googlefree.(*Provider).BatchTranslateText(0x110f470, 0xc00041ff00, 0x1, 0x4, 0xc0000a2598, 0x2, 0xc0000a259a, 0x2, 0x2, 0xc000850230, ...)

/app/googlefree/provider.go:56 +0x186

github.com/yuriizinets/translator/server.TranslateHandler.func1(0xccecc0, 0x110f470, 0x2, 0xc000850230, 0x1, 0x1)

/app/server/handler.go:50 +0x7d

github.com/yuriizinets/translator/aggregator.(*Aggregator).Action(0x10dd220, 0xc0005edad0, 0x0, 0x0, 0xc0005ca140, 0x0, 0x0, 0x0)

/app/aggregator/aggregator.go:32 +0x12c

github.com/yuriizinets/translator/server.TranslateHandler(0xccae40, 0xc000285b20, 0xc000016d00)

/app/server/handler.go:49 +0x152

net/http.HandlerFunc.ServeHTTP(0xc0e2f0, 0xccae40, 0xc000285b20, 0xc000016d00)

/usr/local/go/src/net/http/server.go:2042 +0x44

github.com/yuriizinets/translator/server.Recovery.func1(0xccae40, 0xc000285b20, 0xc000016d00)

/app/server/recovery.go:27 +0x7e

net/http.HandlerFunc.ServeHTTP(0xc0004bbec0, 0xccae40, 0xc000285b20, 0xc000016d00)

/usr/local/go/src/net/http/server.go:2042 +0x44

net/http.(*ServeMux).ServeHTTP(0xc0004b1c00, 0xccae40, 0xc000285b20, 0xc000016d00)

/usr/local/go/src/net/http/server.go:2417 +0x1ad

net/http.serverHandler.ServeHTTP(0xc0004821c0, 0xccae40, 0xc000285b20, 0xc000016d00)

/usr/local/go/src/net/http/server.go:2843 +0xa3

net/http.(*conn).serve(0xc00021e1e0, 0xcccb40, 0xc0000da000)

/usr/local/go/src/net/http/server.go:1925 +0x8ad

created by net/http.(*Server).Serve

/usr/local/go/src/net/http/server.go:2969 +0x36c


goroutine 3114 [select]:

google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc0005cb450, 0x1, 0x0, 0x0, 0x0, 0x0)

/go/pkg/mod/google.golang.org/grpc@v1.31.0/internal/transport/controlbuf.go:395 +0x125

google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc000a699e0, 0x0, 0x0)

/go/pkg/mod/google.golang.org/grpc@v1.31.0/internal/transport/controlbuf.go:515 +0x1d3

google.golang.org/grpc/internal/transport.newHTTP2Client.func3(0xc0001e9a40)

/go/pkg/mod/google.golang.org/grpc@v1.31.0/internal/transport/http2_client.go:356 +0x7b

created by google.golang.org/grpc/internal/transport.newHTTP2Client

/go/pkg/mod/google.golang.org/grpc@v1.31.0/internal/transport/http2_client.go:354 +0x123c


goroutine 3301 [IO wait]:

internal/poll.runtime_pollWait(0x7f305ec568c8, 0x72, 0xcbf220)

/usr/local/go/src/runtime/netpoll.go:220 +0x55

internal/poll.(*pollDesc).wait(0xc000292f18, 0x72, 0xc000358000, 0x12de, 0x12de)

/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45

internal/poll.(*pollDesc).waitRead(...)

/usr/local/go/src/internal/poll/fd_poll_runtime.go:92

internal/poll.(*FD).Read(0xc000292f00, 0xc000358000, 0x12de, 0x12de, 0x0, 0x0, 0x0)

/usr/local/go/src/internal/poll/fd_unix.go:159 +0x1b1

net.(*netFD).Read(0xc000292f00, 0xc000358000, 0x12de, 0x12de, 0x203000, 0x73471b, 0xc000480be0)

/usr/local/go/src/net/fd_posix.go:55 +0x4f

net.(*conn).Read(0xc00033e008, 0xc000358000, 0x12de, 0x12de, 0x0, 0x0, 0x0)

/usr/local/go/src/net/net.go:182 +0x8e

crypto/tls.(*atLeastReader).Read(0xc00076a580, 0xc000358000, 0x12de, 0x12de, 0x22, 0xc4b, 0xc00005f730)

/usr/local/go/src/crypto/tls/conn.go:779 +0x62

bytes.(*Buffer).ReadFrom(0xc000480d00, 0xcbc0e0, 0xc00076a580, 0x40d245, 0xb113e0, 0xbb8b40)

/usr/local/go/src/bytes/buffer.go:204 +0xb1

crypto/tls.(*Conn).readFromUntil(0xc000480a80, 0xcbdda0, 0xc00033e008, 0x5, 0xc00033e008, 0x11)

/usr/local/go/src/crypto/tls/conn.go:801 +0xf3

crypto/tls.(*Conn).readRecordOrCCS(0xc000480a80, 0x0, 0x0, 0x11)

/usr/local/go/src/crypto/tls/conn.go:608 +0x115

crypto/tls.(*Conn).readRecord(...)

/usr/local/go/src/crypto/tls/conn.go:576

crypto/tls.(*Conn).Read(0xc000480a80, 0xc00048b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)

/usr/local/go/src/crypto/tls/conn.go:1252 +0x15f

bufio.(*Reader).Read(0xc000af8360, 0xc0000e6738, 0x9, 0x9, 0x0, 0xc00005fd20, 0x82e9d4)

/usr/local/go/src/bufio/bufio.go:227 +0x222

io.ReadAtLeast(0xcbbf60, 0xc000af8360, 0xc0000e6738, 0x9, 0x9, 0x9, 0xc0004fe260, 0xc00048a000, 0x11)

/usr/local/go/src/io/io.go:314 +0x87

io.ReadFull(...)

/usr/local/go/src/io/io.go:333

net/http.http2readFrameHeader(0xc0000e6738, 0x9, 0x9, 0xcbbf60, 0xc000af8360, 0x0, 0x0, 0x0, 0x0)

/usr/local/go/src/net/http/h2_bundle.go:1477 +0x89

net/http.(*http2Framer).ReadFrame(0xc0000e6700, 0xc00028a140, 0x0, 0x0, 0x0)

/usr/local/go/src/net/http/h2_bundle.go:1735 +0xa5

net/http.(*http2clientConnReadLoop).run(0xc00005ffa8, 0x1, 0x0)

/usr/local/go/src/net/http/h2_bundle.go:8240 +0x8d

net/http.(*http2ClientConn).readLoop(0xc000014180)

/usr/local/go/src/net/http/h2_bundle.go:8168 +0x6f

created by net/http.(*http2Transport).newClientConn

/usr/local/go/src/net/http/h2_bundle.go:7173 +0x66e


goroutine 3591 [IO wait]:

internal/poll.runtime_pollWait(0x7f305ec56e08, 0x72, 0xcbf220)

/usr/local/go/src/runtime/netpoll.go:220 +0x55

internal/poll.(*pollDesc).wait(0xc00017a318, 0x72, 0xc00077a000, 0x1, 0x1)

/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45

internal/poll.(*pollDesc).waitRead(...)

/usr/local/go/src/internal/poll/fd_poll_runtime.go:92

internal/poll.(*FD).Read(0xc00017a300, 0xc00077a0a1, 0x1, 0x1, 0x0, 0x0, 0x0)

/usr/local/go/src/internal/poll/fd_unix.go:159 +0x1b1

net.(*netFD).Read(0xc00017a300, 0xc00077a0a1, 0x1, 0x1, 0xc0000da198, 0xc00075cf68, 0x4741fc)

/usr/local/go/src/net/fd_posix.go:55 +0x4f

net.(*conn).Read(0xc000010048, 0xc00077a0a1, 0x1, 0x1, 0x0, 0x0, 0x0)

/usr/local/go/src/net/net.go:182 +0x8e

net/http.(*connReader).backgroundRead(0xc00077a090)

/usr/local/go/src/net/http/server.go:690 +0x58

created by net/http.(*connReader).startBackgroundRead

/usr/local/go/src/net/http/server.go:686 +0xd5
```

**Comment by yuriizinets** [comment]
Closed with https://github.com/yuriizinets/translator/commit/cc92fe74cb92b12153701732464f019ec23f2002
